In [1]:
import numpy as np

# Résolution Jauges de déformation
E. Roux, USMB, Polytech Annecy-Chambery

## Les mesures des 3 jauges

In [2]:
ea = 500e-6
eb = -200e-6
ec = 300e-6
M = np.array([ea, eb, ec])
print(M)

[ 0.0005 -0.0002  0.0003]


## Les postions des 3 jauges

In [3]:
# Angle phi
pa = 0.
pb = np.deg2rad(120)
pc = np.deg2rad(-120)

## Matrice de rigidité K

In [4]:
ca = np.cos(pa)
sa = np.sin(pa)

cb = np.cos(pb)
sb = np.sin(pb)

cc = np.cos(pc)
sc = np.sin(pc)

In [5]:
K = np.array([[ca**2, 2*sa*ca, sa**2],
             [cb**2, 2*sb*cb, sb**2],
             [cc**2, 2*sc*cc, sc**2]])
print(K)

[[ 1.         0.         0.       ]
 [ 0.25      -0.8660254  0.75     ]
 [ 0.25       0.8660254  0.75     ]]


## Résolution du système
$\vec M = K \vec D$

$\vec D = K^{-1} \vec M$

In [6]:
Kinv = np.linalg.inv(K)
print(Kinv)

[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 5.34156302e-18 -5.77350269e-01  5.77350269e-01]
 [-3.33333333e-01  6.66666667e-01  6.66666667e-01]]


In [7]:
D = np.dot(Kinv,M)
D

array([ 5.00000000e-04,  2.88675135e-04, -1.00000000e-04])

In [8]:
print('E11 = {0:0.3f} µdef'.format(D[0]/1e-6))
print('E12 = {0:0.3f} µdef'.format(D[1]/1e-6))
print('E22 = {0:0.3f} µdef'.format(D[2]/1e-6))

E11 = 500.000 µdef
E12 = 288.675 µdef
E22 = -100.000 µdef
