In [2]:
import numpy as np

# Résolution Jauges de déformation
E. Roux, USMB, Polytech Annecy-Chambery

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Les-mesures-des-3-jauges" data-toc-modified-id="Les-mesures-des-3-jauges-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Les mesures des 3 jauges</a></span></li><li><span><a href="#Les-postions-des-3-jauges" data-toc-modified-id="Les-postions-des-3-jauges-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Les postions des 3 jauges</a></span></li><li><span><a href="#Matrice-de-rigidité-K" data-toc-modified-id="Matrice-de-rigidité-K-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Matrice de rigidité K</a></span></li><li><span><a href="#Résolution-du-système" data-toc-modified-id="Résolution-du-système-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Résolution du système</a></span></li></ul></div>

## Les mesures des 3 jauges

In [34]:
ea = 100e-6
eb = 20e-6
ec = 50e-6
M = np.array([ea, eb, ec])
print(M)

[1.e-04 2.e-05 5.e-05]


## Les postions des 3 jauges

In [47]:
# Angle phi
pa = np.deg2rad(0)
pb = np.deg2rad(30)
pc = np.deg2rad(60)

## Matrice de rigidité K

In [48]:
ca = np.cos(pa)
sa = np.sin(pa)

cb = np.cos(pb)
sb = np.sin(pb)

cc = np.cos(pc)
sc = np.sin(pc)

In [49]:
K = np.array([[ca**2, 2*sa*ca, sa**2],
             [cb**2, 2*sb*cb, sb**2],
             [cc**2, 2*sc*cc, sc**2]])
print(K)

[[1.        0.        0.       ]
 [0.75      0.8660254 0.25     ]
 [0.25      0.8660254 0.75     ]]


## Résolution du système
$\vec M = K \vec D$

$\vec D = K^{-1} \vec M$

In [50]:
Kinv = np.linalg.inv(K)
print(Kinv)

[[ 1.          0.          0.        ]
 [-1.15470054  1.73205081 -0.57735027]
 [ 1.         -2.          2.        ]]


In [39]:
D = np.dot(Kinv,M)
D

array([ 0.0001   , -0.0001097,  0.00016  ])

In [40]:
print('E11 = {0:0.3f} µdef'.format(D[0]/1e-6))
print('E12 = {0:0.3f} µdef'.format(D[1]/1e-6))
print('E22 = {0:0.3f} µdef'.format(D[2]/1e-6))

E11 = 100.000 µdef
E12 = -109.697 µdef
E22 = 160.000 µdef
